/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as NameContractJson } from "../forward_name_resolver/Name.ral.json";
import { getContractByCodeHash } from "./contracts";
import { Trait, AllStructs } from "./types";

// Custom types for the contract
export namespace NameTypes {
  export type Fields = {
    collectionId: HexString;
    nftIndex: bigint;
    name: HexString;
    capitalisation: HexString;
    address: Address;
    expires: bigint;
  };

  export type State = ContractState<Fields>;

  export type MetadataUpdatedEvent = ContractEvent<{}>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint]>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDescription: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getImage: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getTraitCount: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTraitAtIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<Trait>;
    };
    getNFTIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getCapitalisation: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getExpires: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    setAddress: {
      params: CallContractParams<{ newAddress: Address }>;
      result: CallContractResult<null>;
    };
    setCapitalisation: {
      params: CallContractParams<{ newCapitalisation: HexString }>;
      result: CallContractResult<null>;
    };
    setExpires: {
      params: CallContractParams<{ newExpires: bigint }>;
      result: CallContractResult<null>;
    };
    delete: {
      params: CallContractParams<{ refundAddress: Address }>;
      result: CallContractResult<null>;
    };
    getTraits: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[Trait, Trait, Trait]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> =
    Callss["length"] extends 1
      ? MultiCallResults<Callss[0]>
      : { [index in keyof Callss]: MultiCallResults<Callss[index]> };

  export interface SignExecuteMethodTable {
    getTokenUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCollectionIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDescription: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getImage: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTraitCount: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTraitAtIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getNFTIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCapitalisation: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getExpires: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAddress: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setAddress: {
      params: SignExecuteContractMethodParams<{ newAddress: Address }>;
      result: SignExecuteScriptTxResult;
    };
    setCapitalisation: {
      params: SignExecuteContractMethodParams<{ newCapitalisation: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    setExpires: {
      params: SignExecuteContractMethodParams<{ newExpires: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    delete: {
      params: SignExecuteContractMethodParams<{ refundAddress: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getTraits: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<NameInstance, NameTypes.Fields> {
  encodeFields(fields: NameTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { MetadataUpdated: 0 };
  consts = {
    ErrorCodes: {
      OnlyParentAllowed: BigInt("0"),
      NFTNotFound: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
      OnlyNftOwnerAllowed: BigInt("3"),
      NameHasNotExpired: BigInt("4"),
      CannotRenewName: BigInt("5"),
      TokenAlreadyGenerated: BigInt("6"),
      ReverseAddressNotFound: BigInt("7"),
      OnlyNftOwnerOrHolderAllowed: BigInt("8"),
      IncorrectFarmInputAmount: BigInt("9"),
      CropHasNotExpired: BigInt("10"),
      FarmInputAmountNotConsumed: BigInt("11"),
      FarmAlreadyGenerated: BigInt("12"),
    },
    Keys: { Names: "01", Token: "02", Farm: "03" },
  };

  at(address: string): NameInstance {
    return new NameInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenUri", params, getContractByCodeHash);
    },
    getCollectionIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint]>> => {
      return testMethod(
        this,
        "getCollectionIndex",
        params,
        getContractByCodeHash
      );
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDescription: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getDescription", params, getContractByCodeHash);
    },
    getImage: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getImage", params, getContractByCodeHash);
    },
    getTraitCount: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTraitCount", params, getContractByCodeHash);
    },
    getTraitAtIndex: async (
      params: TestContractParamsWithoutMaps<NameTypes.Fields, { index: bigint }>
    ): Promise<TestContractResultWithoutMaps<Trait>> => {
      return testMethod(this, "getTraitAtIndex", params, getContractByCodeHash);
    },
    getNFTIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getNFTIndex", params, getContractByCodeHash);
    },
    getCapitalisation: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCapitalisation",
        params,
        getContractByCodeHash
      );
    },
    getExpires: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getExpires", params, getContractByCodeHash);
    },
    getAddress: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getAddress", params, getContractByCodeHash);
    },
    setAddress: async (
      params: TestContractParamsWithoutMaps<
        NameTypes.Fields,
        { newAddress: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setAddress", params, getContractByCodeHash);
    },
    setCapitalisation: async (
      params: TestContractParamsWithoutMaps<
        NameTypes.Fields,
        { newCapitalisation: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "setCapitalisation",
        params,
        getContractByCodeHash
      );
    },
    setExpires: async (
      params: TestContractParamsWithoutMaps<
        NameTypes.Fields,
        { newExpires: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setExpires", params, getContractByCodeHash);
    },
    delete: async (
      params: TestContractParamsWithoutMaps<
        NameTypes.Fields,
        { refundAddress: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "delete", params, getContractByCodeHash);
    },
    getTraits: async (
      params: Omit<
        TestContractParamsWithoutMaps<NameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<[Trait, Trait, Trait]>> => {
      return testMethod(this, "getTraits", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const Name = new Factory(
  Contract.fromJson(
    NameContractJson,
    "",
    "c87c1214c5bc7212c8c2ec57c8ea4876addee40b45c268bac30cfbd15cd79008",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class NameInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NameTypes.State> {
    return fetchContractState(Name, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMetadataUpdatedEvent(
    options: EventSubscribeOptions<NameTypes.MetadataUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Name.contract,
      this,
      options,
      "MetadataUpdated",
      fromCount
    );
  }

  view = {
    getTokenUri: async (
      params?: NameTypes.CallMethodParams<"getTokenUri">
    ): Promise<NameTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        Name,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionIndex: async (
      params?: NameTypes.CallMethodParams<"getCollectionIndex">
    ): Promise<NameTypes.CallMethodResult<"getCollectionIndex">> => {
      return callMethod(
        Name,
        this,
        "getCollectionIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: NameTypes.CallMethodParams<"getName">
    ): Promise<NameTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Name,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDescription: async (
      params?: NameTypes.CallMethodParams<"getDescription">
    ): Promise<NameTypes.CallMethodResult<"getDescription">> => {
      return callMethod(
        Name,
        this,
        "getDescription",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getImage: async (
      params?: NameTypes.CallMethodParams<"getImage">
    ): Promise<NameTypes.CallMethodResult<"getImage">> => {
      return callMethod(
        Name,
        this,
        "getImage",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTraitCount: async (
      params?: NameTypes.CallMethodParams<"getTraitCount">
    ): Promise<NameTypes.CallMethodResult<"getTraitCount">> => {
      return callMethod(
        Name,
        this,
        "getTraitCount",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTraitAtIndex: async (
      params: NameTypes.CallMethodParams<"getTraitAtIndex">
    ): Promise<NameTypes.CallMethodResult<"getTraitAtIndex">> => {
      return callMethod(
        Name,
        this,
        "getTraitAtIndex",
        params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params?: NameTypes.CallMethodParams<"getNFTIndex">
    ): Promise<NameTypes.CallMethodResult<"getNFTIndex">> => {
      return callMethod(
        Name,
        this,
        "getNFTIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCapitalisation: async (
      params?: NameTypes.CallMethodParams<"getCapitalisation">
    ): Promise<NameTypes.CallMethodResult<"getCapitalisation">> => {
      return callMethod(
        Name,
        this,
        "getCapitalisation",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getExpires: async (
      params?: NameTypes.CallMethodParams<"getExpires">
    ): Promise<NameTypes.CallMethodResult<"getExpires">> => {
      return callMethod(
        Name,
        this,
        "getExpires",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAddress: async (
      params?: NameTypes.CallMethodParams<"getAddress">
    ): Promise<NameTypes.CallMethodResult<"getAddress">> => {
      return callMethod(
        Name,
        this,
        "getAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setAddress: async (
      params: NameTypes.CallMethodParams<"setAddress">
    ): Promise<NameTypes.CallMethodResult<"setAddress">> => {
      return callMethod(
        Name,
        this,
        "setAddress",
        params,
        getContractByCodeHash
      );
    },
    setCapitalisation: async (
      params: NameTypes.CallMethodParams<"setCapitalisation">
    ): Promise<NameTypes.CallMethodResult<"setCapitalisation">> => {
      return callMethod(
        Name,
        this,
        "setCapitalisation",
        params,
        getContractByCodeHash
      );
    },
    setExpires: async (
      params: NameTypes.CallMethodParams<"setExpires">
    ): Promise<NameTypes.CallMethodResult<"setExpires">> => {
      return callMethod(
        Name,
        this,
        "setExpires",
        params,
        getContractByCodeHash
      );
    },
    delete: async (
      params: NameTypes.CallMethodParams<"delete">
    ): Promise<NameTypes.CallMethodResult<"delete">> => {
      return callMethod(Name, this, "delete", params, getContractByCodeHash);
    },
    getTraits: async (
      params?: NameTypes.CallMethodParams<"getTraits">
    ): Promise<NameTypes.CallMethodResult<"getTraits">> => {
      return callMethod(
        Name,
        this,
        "getTraits",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getTokenUri: async (
      params: NameTypes.SignExecuteMethodParams<"getTokenUri">
    ): Promise<NameTypes.SignExecuteMethodResult<"getTokenUri">> => {
      return signExecuteMethod(Name, this, "getTokenUri", params);
    },
    getCollectionIndex: async (
      params: NameTypes.SignExecuteMethodParams<"getCollectionIndex">
    ): Promise<NameTypes.SignExecuteMethodResult<"getCollectionIndex">> => {
      return signExecuteMethod(Name, this, "getCollectionIndex", params);
    },
    getName: async (
      params: NameTypes.SignExecuteMethodParams<"getName">
    ): Promise<NameTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(Name, this, "getName", params);
    },
    getDescription: async (
      params: NameTypes.SignExecuteMethodParams<"getDescription">
    ): Promise<NameTypes.SignExecuteMethodResult<"getDescription">> => {
      return signExecuteMethod(Name, this, "getDescription", params);
    },
    getImage: async (
      params: NameTypes.SignExecuteMethodParams<"getImage">
    ): Promise<NameTypes.SignExecuteMethodResult<"getImage">> => {
      return signExecuteMethod(Name, this, "getImage", params);
    },
    getTraitCount: async (
      params: NameTypes.SignExecuteMethodParams<"getTraitCount">
    ): Promise<NameTypes.SignExecuteMethodResult<"getTraitCount">> => {
      return signExecuteMethod(Name, this, "getTraitCount", params);
    },
    getTraitAtIndex: async (
      params: NameTypes.SignExecuteMethodParams<"getTraitAtIndex">
    ): Promise<NameTypes.SignExecuteMethodResult<"getTraitAtIndex">> => {
      return signExecuteMethod(Name, this, "getTraitAtIndex", params);
    },
    getNFTIndex: async (
      params: NameTypes.SignExecuteMethodParams<"getNFTIndex">
    ): Promise<NameTypes.SignExecuteMethodResult<"getNFTIndex">> => {
      return signExecuteMethod(Name, this, "getNFTIndex", params);
    },
    getCapitalisation: async (
      params: NameTypes.SignExecuteMethodParams<"getCapitalisation">
    ): Promise<NameTypes.SignExecuteMethodResult<"getCapitalisation">> => {
      return signExecuteMethod(Name, this, "getCapitalisation", params);
    },
    getExpires: async (
      params: NameTypes.SignExecuteMethodParams<"getExpires">
    ): Promise<NameTypes.SignExecuteMethodResult<"getExpires">> => {
      return signExecuteMethod(Name, this, "getExpires", params);
    },
    getAddress: async (
      params: NameTypes.SignExecuteMethodParams<"getAddress">
    ): Promise<NameTypes.SignExecuteMethodResult<"getAddress">> => {
      return signExecuteMethod(Name, this, "getAddress", params);
    },
    setAddress: async (
      params: NameTypes.SignExecuteMethodParams<"setAddress">
    ): Promise<NameTypes.SignExecuteMethodResult<"setAddress">> => {
      return signExecuteMethod(Name, this, "setAddress", params);
    },
    setCapitalisation: async (
      params: NameTypes.SignExecuteMethodParams<"setCapitalisation">
    ): Promise<NameTypes.SignExecuteMethodResult<"setCapitalisation">> => {
      return signExecuteMethod(Name, this, "setCapitalisation", params);
    },
    setExpires: async (
      params: NameTypes.SignExecuteMethodParams<"setExpires">
    ): Promise<NameTypes.SignExecuteMethodResult<"setExpires">> => {
      return signExecuteMethod(Name, this, "setExpires", params);
    },
    delete: async (
      params: NameTypes.SignExecuteMethodParams<"delete">
    ): Promise<NameTypes.SignExecuteMethodResult<"delete">> => {
      return signExecuteMethod(Name, this, "delete", params);
    },
    getTraits: async (
      params: NameTypes.SignExecuteMethodParams<"getTraits">
    ): Promise<NameTypes.SignExecuteMethodResult<"getTraits">> => {
      return signExecuteMethod(Name, this, "getTraits", params);
    },
  };

  async multicall<Callss extends NameTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<NameTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      Name,
      this,
      callss,
      getContractByCodeHash
    )) as NameTypes.MulticallReturnType<Callss>;
  }
}
