/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as DeleteExpiredScriptJson } from "../name_service/scripts/DeleteExpired.ral.json";
import { default as GenerateTokenScriptJson } from "../name_service/scripts/GenerateToken.ral.json";
import { default as MintNameScriptJson } from "../name_service/scripts/MintName.ral.json";
import { default as RemoveReverseAddressNameScriptJson } from "../name_service/scripts/RemoveReverseAddressName.ral.json";
import { default as RenewNameScriptJson } from "../name_service/scripts/RenewName.ral.json";
import { default as SetAddressScriptJson } from "../name_service/scripts/SetAddress.ral.json";
import { default as SetCapitalisationScriptJson } from "../name_service/scripts/SetCapitalisation.ral.json";
import { default as SetReverseAddressNameScriptJson } from "../name_service/scripts/SetReverseAddressName.ral.json";

export const DeleteExpired = new ExecutableScript<{
  forwardNameResolverId: HexString;
  name: HexString;
}>(Script.fromJson(DeleteExpiredScriptJson, "", []));

export const GenerateToken = new ExecutableScript<{
  forwardNameResolverId: HexString;
}>(Script.fromJson(GenerateTokenScriptJson, "", []));

export const MintName = new ExecutableScript<{
  forwardNameResolverId: HexString;
  name: HexString;
  capitalisation: HexString;
}>(Script.fromJson(MintNameScriptJson, "", []));

export const RemoveReverseAddressName = new ExecutableScript<{
  forwardNameResolverId: HexString;
}>(Script.fromJson(RemoveReverseAddressNameScriptJson, "", []));

export const RenewName = new ExecutableScript<{
  forwardNameResolverId: HexString;
  name: HexString;
}>(Script.fromJson(RenewNameScriptJson, "", []));

export const SetAddress = new ExecutableScript<{
  forwardNameResolverId: HexString;
  name: HexString;
  address: Address;
}>(Script.fromJson(SetAddressScriptJson, "", []));

export const SetCapitalisation = new ExecutableScript<{
  forwardNameResolverId: HexString;
  name: HexString;
  newCapitalisation: HexString;
}>(Script.fromJson(SetCapitalisationScriptJson, "", []));

export const SetReverseAddressName = new ExecutableScript<{
  forwardNameResolverId: HexString;
  name: HexString;
}>(Script.fromJson(SetReverseAddressNameScriptJson, "", []));
